version: '3'

services:
  qnn:
    container_name: qnn
    build: 
      context: .
      shm_size: '8gb'
    shm_size: '8gb'
    network_mode: 'bridge'
    privileged: true
    environment:
      - IBMQ_TOKEN=${IBMQ_TOKEN}
    ports:
      - "8008:8888"
    volumes:
      - ./code:/code
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
